Casgem_Proje/Controllers/AboutUIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Casgem_Proje.Models.Entities;

namespace Casgem_Proje.Controllers
{
    public class AboutUIController : Controller
    {
        CasgemPortfolioEntities1 db = new CasgemPortfolioEntities1();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PartialBreadcrumb()
        {
            return PartialView();
        }
        public ActionResult PartialAbout()
        {
            var values = db.TblSocialMedia.ToList();
            ViewBag.Name = db.TblUIAbout.Select(x => x.Name).FirstOrDefault();
            ViewBag.Surname = db.TblUIAbout.Select(x => x.Surname).FirstOrDefault();
            ViewBag.Address = db.TblUIAbout.Select(x => x.Adress).FirstOrDefault();
            ViewBag.Description = db.TblUIAbout.Select(x => x.Description).FirstOrDefault();
            ViewBag.PhoneNumber = db.TblUIAbout.Select(x => x.PhoneNumber).FirstOrDefault();
            ViewBag.ImageUrl = db.TblUIAbout.Select(x => x.Imageurl).FirstOrDefault();
            ViewBag.Mail = db.TblUIAbout.Select(x => x.Mail).FirstOrDefault();

            return PartialView(values);
        }
        public ActionResult PartialAbout2()
        {
            return PartialView();
        }
       
        public ActionResult PartialAbout3()
        {
            return PartialView();
        } 
        public ActionResult PartialNewsletter()
        {
            return PartialView();
        }
        public ActionResult PartialAchievements()
        {
            var values = db.TblProje.ToList();
            return PartialView(values);
        }
    }
}

Casgem_Proje/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Casgem_Proje.Models.Entities;

namespace Casgem_Proje.Controllers
{
    public class PortfolioController : Controller
    {
        CasgemPortfolioEntities1 db = new CasgemPortfolioEntities1();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialFeature()
        {
            ViewBag.FeatureTitle = db.TblFeature.Select(x => x.FeatureTitle).FirstOrDefault();
            ViewBag.FeatureDescription = db.TblFeature.Select(x => x.FeatureDescription).FirstOrDefault();
            ViewBag.FeatureImageURl = db.TblFeature.Select(x => x.FeatureImageURl).FirstOrDefault();
            return PartialView();
        }
        public PartialViewResult MyResume()
        {
            var values = db.TblResume.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialStatistic()
        {
            ViewBag.totalService = db.TblService.Count();
            ViewBag.totalMessage = db.TblMessage.Count();
            ViewBag.totalThanksMessage = db.TblMessage.Where(x => x.MessageSubject == "Teşekkür").Count();
            ViewBag.happyCustomer = 12;
            return PartialView();
        }
        public PartialViewResult PartialWhoAmI()
        {
            ViewBag.AboutTitle = db.TblAbout.Select(x => x.AboutTitle).FirstOrDefault();
            ViewBag.AboutDescription = db.TblAbout.Select(x => x.AboutDescription).FirstOrDefault();
            ViewBag.AboutImageURl = db.TblAbout.Select(x => x.AboutImageUrl).FirstOrDefault();
            ViewBag.dosya = db.TblAbout.Select(x => x.AboutFile).FirstOrDefault();
            return PartialView();
        }
        [HttpGet]
        public ActionResult Download()
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(this.Server.MapPath("\\Templates\\SelviSümeyraYıdırımCv.pdf"));
            string fileName = "SelviSümeyraYıdırımCv.pdf";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        public PartialViewResult PartialService()
        { var values = db.TblService.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialFooter()
        {
            var values = db.TblSocialMedia.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialScript()
        {
           
            return PartialView();
        }
        public PartialViewResult PartialTestimonial()
        {
            var values = db.TblReference.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialVideo()
        {
            var values = db.TblVideo.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialFreelance()
        {
            return PartialView();
        }
    }
}

Casgem_Proje/Views/AboutUI/Index.cshtml
@{

    Layout = null;
}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!doctype html>
<html lang="en">

@Html.Action("PartialHead","Portfolio")

<body>
    <!-- header -->
    @Html.Action("PartialNavbar","Portfolio")
    <!-- //header -->
    <!-- about breadcrumb -->
    @Html.Action("PartialBreadcrumb")
    <!-- //about breadcrumb -->
    <!-- about page about section -->
    @Html.Action("PartialAbout")
    <!-- //about page about section -->
    <!-- about page second section -->
    @Html.Action("PartialAbout2")
    <!-- //about page about section -->
    <!-- about page third section -->
    @Html.Action("PartialAbout3")
    <!-- about page third section -->
    <!-- subscribe block -->
    @Html.Action("PartialNewsletter")
    <!-- //subscribe block -->
    <!-- achievements block -->
    @Html.Action("PartialAchievements")
    <!-- //achievements block -->
    <!-- Footer -->
    @Html.Action("PartialFooter","Portfolio")
    <!-- //Footer -->
    <!-- all js scripts and files here -->
    @Html.Action("PartialScript","Portfolio")

Casgem_Proje/Views/AboutUI/PartialAbout.cshtml
@model List<Casgem_Proje.Models.Entities.TblSocialMedia>
<section class="w3l-aboutblock1" id="about">
    <div class="midd-w3 py-5">
        <div class="container py-lg-5 py-md-3">
            <div class="row">
                <div class="col-lg-4">
                    <div class="position-relative">
                        <img src="@ViewBag.ImageUrl"  alt="" class="radius-image img-fluid">
                    </div>
                </div>
                <div class="col-lg-8 mt-lg-0 mt-5">
                    <h5 class="title-small mb-2">Merhaba Ben Junior Developer</h5>
                    <p class="mt-4">
                        @ViewBag.Description
                    </p>
                    <div class="my-info mt-4">
                        <div class="single-info">
                            <span>Ad Soyadı:</span>
                            <p>@ViewBag.Name  @ViewBag.Surname</p>
                        </div>
                        <div class="single-info">
                            <span>Telefon Numarası:</span>
                            <p>@ViewBag.PhoneNumber</p>
                        </div>
                        <div class="single-info">
                            <span>Adres:</span>
                            <p>@ViewBag.Address</p>
                        </div>
                        <div class="single-info">
                            <span>Mail:</span>
                            <p><a href="@ViewBag.Mail">@ViewBag.Mail</a></p>
                        </div>
                    </div>
                    <div class="my-social mt-lg-5 mt-4">
                        <a href="/Portfolio/Download/" class="btn btn-style btn-primary">Cv'mi İndir</a>
                        <ul class="social m-0 p-0">
                         
                            @foreach (var item in Model)
                            {
                            <li><a href="@item.SocialMediaUrl"><span class=" @item.SocialMediaIcon"></span></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Casgem_Proje/Views/AboutUI/PartialAbout2.cshtml
<div class="py-5 w3l-resume">
    <div class="container py-lg-5 py-3">
        <h5 class="title-small mb-2"> Merhaba</h5>
        <h3 class="title-big mb-4">İşletmenize hemen yeni bir Yaratıcı başlangıç ​​sağlayabilirim!</h3>
        <p>
            Birleşik Krallık'ta yaşayan bir serbest çalışanım ve yıllardır en son tasarım trendlerine uyan dikkate değer UX/UI tasarımları ve web siteleri inşa ediyorum. Bir vizyonun ve bir fikrin anlamlı ve faydalı ürünlere dönüştürülmesine yardımcı oluyorum. Ürün gelişimi için keskin bir göze sahip olmak, görevleri önceliklendirmeme, hızlı yineleme yapmama ve daha hızlı teslim etmeme yardımcı oluyor
        </p>
        <div class="row features-w3pvt-main mt-5 pt-md-3" id="features">
            <div class="col-lg-4 col-md-6 feature-gird">
                <div class="row features-hny-inner-gd">
                    <div class="col-md-2 col-2 featured_grid_left">
                        <div class="icon_left_grid">
                            <span class="fa fa-laptop" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="col-md-10 col-10 featured_grid_right_info">
                        <h4><a class="link-hny" href="#url">Responsive Design </a></h4>
                        <p>Lorem ipsum dolor sit amet elit consec tetur adipisi elit., rem!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 feature-gird mt-md-0 mt-4">
                <div class="row features-hny-inner-gd">
                    <div class="col-md-2 col-2 featured_grid_left">
                        <div class="icon_left_grid">
                            <span class="fa fa-pencil-square-o" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="col-md-10 col-10 featured_grid_right_info">
                        <h4><a class="link-hny" href="#url">Powerful Editor </a></h4>
                        <p>Lorem ipsum dolor sit amet elit consec tetur adipisi elit., rem!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 feature-gird mt-lg-0 mt-md-5 mt-4">
                <div class="row features-hny-inner-gd">
                    <div class="col-md-2 col-2 featured_grid_left">
                        <div class="icon_left_grid">
                            <span class="fa fa-desktop" aria-hidden="true"></span>
                        </div>
                    </div>
                    <div class="col-md-10 col-10 featured_grid_right_info">
                        <h4><a class="link-hny" href="#url">Creative Design </a></h4>
                        <p>Lorem ipsum dolor sit amet elit consec tetur adipisi elit., rem!</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Casgem_Proje/Views/AboutUI/PartialAbout3.cshtml
<section class="w3l-content-6 py-5">
    <div class="content-6-mian py-lg-5 py-md-4">
        <div class="container">
            <div class="content-info-in row">
                <div class="content-gd col-lg-5">
                    <h3 class="title-big mb-4">Başarıya Ulaşma Arzusu ile Motive Edilen</h3>
                    <p>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorem, odit! Perspiciatis et
                        consequuntur non, modi quo mollitia labore laborum voluptas quia officiis fugit soluta molestias
                        quaerat sapiente sunt.
                    </p>
                </div>
                <div class="content-gd col-lg-6 offset-lg-1">
                    <div class="progress-info">
                        <h6 class="progress-tittle">Kullanıcı Arayüzü/UX Tasarımı</h6>
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 80%"
                                 aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                    <div class="progress-info">
                        <h6 class="progress-tittle">
                            Fikirler ve Teknoloji
                        </h6>
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 95%"
                                 aria-valuenow="95" aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                    <div class="progress-info">
                        <h6 class="progress-tittle">Marka Tasarımı</h6>
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 55%"
                                 aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                    <div class="progress-info mb-0">
                        <h6 class="progress-tittle">Duyarlı Web Tasarımı</h6>
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 80%"
                                 aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Casgem_Proje/Views/AboutUI/PartialAchievements.cshtml
@model List<Casgem_Proje.Models.Entities.TblProje>
<section class="w3l-services">
    <div class="w3l-achievements py-5" id="services">
        <div class="container py-lg-5">
            <h3 class="title-big text-center mb-sm-5 mb-4">Projelerim</h3>
            <div class="row">
                @foreach (var item in Model)
                {
                <div class="col-lg-6 item">
                    <div class="card">
                        <div class="box-wrap">
                            <div class="icon">
                                <span class="fa fa-globe"></span>
                            </div>
                            <h4><a href="#url">@item.ProjeTitle</a></h4>
                            <p>
                                @item.ProjeDescription
                            </p>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</section>

Casgem_Proje/Views/AboutUI/PartialBreadcrumb.cshtml
<section class="w3l-about-breadcrumb text-center">
    <div class="breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4">
        <div class="container py-2">
            <h2 class="title">Hakkımda</h2>
            <ul class="breadcrumbs-custom-path mt-2">
                <li><a href="#url">Ana Sayfa</a></li>
                <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> Hakkımda</li>
            </ul>
        </div>
    </div>
</section>

Casgem_Proje/Views/AboutUI/PartialNewsletter.cshtml
<div class="abouthy-img-grids">
    <div class="img-one">
        <img src="~/Templates/alexander-starter/assets/images/g5.jpg" alt=" " class="img-fluid">
    </div>
    <div class="img-one content-mid">
        <h3 class="title-big"> Güncel kalın, Ücretsiz Bültene abone olun! </h3>
        <form action="#url" method="GET" class="subscribe-form">
            <input type="email" name="email" placeholder="Enter your email" required>
            <button type="submit" class="btn">Abone Ol</button>
        </form>

    </div>
    <div class="img-one">
        <img src="~/Templates/alexander-starter/assets/images/g3.jpg" alt=" " class="img-fluid">
    </div>
</div>